name: 'rpmlint action'
author: 'EyeCantCU'
description: 'Checks for errors in RPMs via rpmlint'
inputs:
  rpmfiles:
    description: 'Files to be validated by rpmlint'
    required: false
  help:
    description: 'Show help message and exit'
    required: false
  version:
    description: 'Show package version and exit'
    required: false
  config:
    description: 'Load up additional configuration data from specified path (file or directory with *.toml files)'
    required: false
  explain:
    description: 'Provide detailed explanation for one specific message id'
    required: false
  rpmlintrc:
    description: 'Load up specified rpmlintrc file'
    required: false
  verbose:
    description: 'Provide detailed explanations where available'
    required: false
  print-config:
    description: 'Print the settings that are in effect when using the rpmlint'
    required: false
  installed:
    description: 'Installed packages to be validated by rpmlint'
    required: false
  time-report:
    description: 'Print time report for run checks'
    required: false
  profile:
    description: 'Print cProfile report'
    required: false
  strict:
    description: 'Treat all messages as errors'
    required: false
  permissive:
    description: 'Treat individual errors as non-fatal'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install rpmlint
      shell: bash
      run: sudo apt install -yq rpmlint

    - name: Perform rpmlint
      shell: bash
      run: |
        ARGUMENTS=""
        if [[ -n "${{ inputs.help }}" ]]; then ARGUMENTS+=" -h "; fi
        if [[ -n "${{ inputs.version }}" ]]; then ARGUMENTS+=" -V "; fi
        if [[ -n "${{ inputs.config }}" ]]; then ARGUMENTS+=" -c ${{ inputs.config }} "; fi
        if [[ -n "${{ inputs.explain }}" ]]; then ARGUMENTS+=" -e ${{ inputs.explain }} "; fi
        if [[ -n "${{ inputs.rpmlintrc }}" ]]; then ARGUMENTS+=" -r ${{ inputs.rpmlintrc }} "; fi
        if [[ -n "${{ inputs.verbose }}" ]]; then ARGUMENTS+=" -v "; fi
        if [[ -n "${{ inputs.print-config }}" ]]; then ARGUMENTS+=" -p "; fi
        if [[ -n "${{ inputs.installed }}" ]]; then ARGUMENTS+=" -i ${{ inputs.installed }} "; fi
        if [[ -n "${{ inputs.time-report }}" ]]; then ARGUMENTS+=" -t "; fi
        if [[ -n "${{ inputs.profile }}" ]]; then ARGUMENTS+=" -T "; fi
        if [[ -n "${{ inputs.strict }}" ]]; then ARGUMENTS+=" -s "; fi
        if [[ -n "${{ inputs.permissive }}" ]]; then ARGUMENTS+=" -p "; fi
        if [[ -n "${{ inputs.rpmfiles }}" ]]; then ARGUMENTS+=" ${{ inputs.rpmfiles }} "; fi
        ARGUMENTS=$(echo "$ARGUMENTS" | xargs)
        rpmlint $ARGUMENTS
