name: 'rpmlint action'
author: 'EyeCantCU'
description: 'Checks for errors in RPMs via rpmlint'
inputs:
  rpmfiles:
    description: 'Files to be validated by rpmlint'
    required: false
  help:
    description: 'Show help message and exit'
    required: false
  version:
    description: 'Show package version and exit'
    required: false
  config:
    description: 'Load up additional configuration data from specified path (file or directory with *.toml files)'
    required: false
  explain:
    description: 'Provide detailed explanation for one specific message id'
    required: false
  rpmlintrc:
    description: 'Load up specified rpmlintrc file'
    required: false
  verbose:
    description: 'Provide detailed explanations where available'
    required: false
  print-config:
    description: 'Print the settings that are in effect when using the rpmlint'
    required: false
  installed:
    description: 'Installed packages to be validated by rpmlint'
    required: false
  time-report:
    description: 'Print time report for run checks'
    required: false
  profile:
    description: 'Print cProfile report'
    required: false
  strict:
    description: 'Treat all messages as errors'
    required: false
  permissive:
    description: 'Treat individual errors as non-fatal'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    RPMFILES: ${{ inputs.rpmfiles }}
    HELP: ${{ inputs.help }}
    VERSION: ${{ inputs.version }}
    CONFIG: ${{ inputs.config }}
    EXPLAIN: ${{ inputs.explain }}
    RPMLINTRC: ${{ inputs.rpmlintrc }}
    VERBOSE: ${{ inputs.verbose }}
    PRINT_CONFIG: ${{ inputs.print-config }}
    INSTALLED: ${{ inputs.installed }}
    TIME_REPORT: ${{ inputs.time-report }}
    PROFILE: ${{ inputs.profile }}
    STRICT: ${{ inputs.strict }}
    PERMISSIVE: ${{ inputs.permissive }}
