name: Test Action
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
  merge_group:
  workflow_dispatch:

jobs:
  push-ghcr:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
      - name: Perform checkout
        uses: actions/checkout@v4

      - name: Fetch spec
        run: |
          wget https://raw.githubusercontent.com/ublue-os/packages/main/staging/devpod/devpod.spec

      - name: Test rpmlint
        uses: ./
        with:
          rpmfiles: ./devpod.spec
